/**
 * PHASE 2B-2D — A3 R38A: CROSS-GENERATION SLOT-AUTHORITY REFUSALS.
 *
 * Fail closed. A refusal is thrown, never returned as a slot status, so that
 * no partial cross-generation resolution - some slots minted, one refused -
 * can exist for a caller to consume. Messages name field categories,
 * namespace-local positions and chain positions only: never an organisation,
 * eche row key, run reference, URL, host or sealed path. PURE.
 */

export const CROSS_GENERATION_REFUSAL_CODES = Object.freeze([
  'INPUT_SHAPE_INVALID',
  'RESOLUTION_GENERATION_UNSUPPORTED',
  'GENERATION1_PREFIX_INVALID',
  'LEDGER_NAMESPACE_INVALID',
  'LEDGER_BINDING_INVALID',
  'GENERATION2_STARTING_STATE_MISMATCH',
  'GENERATION2_SCHEDULE_INVALID',
  'GENERATION2_LEDGER_VOCABULARY_INVALID',
  'GENERATION2_LEDGER_ORDER_INVALID',
  'GENERATION2_LEDGER_HASH_CHAIN_BROKEN',
  'GENERATION2_RESERVE_EXHAUSTED',
  'GENERATION2_RESERVE_NOT_MONOTONIC',
  'GENERATION2_RESERVE_IDENTITY_MISMATCH',
  'GENERATION2_RESERVE_REUSED',
  'GENERATION2_SLOT_MISMATCH',
  'GENERATION2_SPLIT_MISMATCH',
  'GENERATION2_REASON_INVALID',
  'GENERATION2_CHAIN_ROOT_INVALID',
  'GENERATION2_CHAIN_DISCONTINUOUS',
  'SOURCE_IDENTITY_INVALID',
  'SOURCE_NAMESPACE_MISMATCH',
  'FACT_KIND_NOT_TERMINAL_ADJUDICATION',
  'FACT_GENERATION_INVALID',
  'FACT_GENERATION_RELABELLED',
  'FACT_DISPOSITION_INVALID',
  'FACT_SPLIT_MISMATCH',
  'FACT_OCCUPANT_NOT_IN_SLOT_CHAIN',
  'FACT_GENERATION_CANNOT_AUTHORISE_OCCUPANT',
  'FACT_PROVENANCE_INVALID',
  'ACQUISITION_OF_RECORD_INVALID',
  'RECOVERY_NOT_SELECTED_BY_ADJUDICATION',
  'DUPLICATE_TERMINAL_ADJUDICATION',
  'REPLACEMENT_AFTER_TERMINAL_SUCCESS',
  'REPLACEMENT_REASON_CONTRADICTS_ADJUDICATION',
  'ADJUDICATION_REGISTRY_INVALID',
  'CARRY_FORWARD_ADMISSION_INVALID',
  'CARRY_FORWARD_ADMISSION_MISSING',
  'CARRY_FORWARD_ADMISSION_MISMATCH',
  'CARRY_FORWARD_ADMISSION_DUPLICATE',
  'CARRY_FORWARD_SUPERSEDED',
  'NOT_A_MINTED_R17_AUTHORITY',
  'NOT_A_MINTED_CROSS_GENERATION_AUTHORITY',
  'CONTINUITY_SLOT_MISMATCH',
  'CONTINUITY_DUPLICATE_SELECTION_INDEX',
  'CONTINUITY_RELABEL_DETECTED',
  'CONTINUITY_CARRY_FORWARD_NOT_GENUINE',
] as const);
export type CrossGenerationRefusalCode = (typeof CROSS_GENERATION_REFUSAL_CODES)[number];

export class A3CrossGenerationSlotAuthorityRefusal extends Error {
  constructor(
    readonly code: CrossGenerationRefusalCode,
    message: string,
  ) {
    super(`${code}: ${message}`);
    this.name = 'A3CrossGenerationSlotAuthorityRefusal';
  }
}

export function refuseCrossGeneration(code: CrossGenerationRefusalCode, message: string): never {
  throw new A3CrossGenerationSlotAuthorityRefusal(code, message);
}
