/**
 * PHASE 2B-2D — A3 CORPUS TOOLING PREPARATION CONTRACTS.
 *
 * Pure constants only. No database, filesystem, network, clock or randomness.
 */

export const SET_P_RANK_SALT = 'SET_P_V2_R2';
export const SET_R_RANK_SALT = 'SET_R_V2_R2';

export const SET_P_MAX_PAGES_PER_ORGANISATION = 8;
export const SET_R_MAX_PAGES_PER_ORGANISATION = 4;

export const ORGANISATION_GATE_SHARE_CAP_NUMERATOR = 1;
export const ORGANISATION_GATE_SHARE_CAP_DENOMINATOR = 10;

export const REQUIRED_SPLIT_ORGANISATION_COUNTS = {
  DEV_TRAIN: 20,
  DEV_CONFIRM: 45,
  FINAL_HOLDOUT: 45,
} as const;

export const REQUIRED_TOTAL_ORGANISATIONS = 110;

export const A3_PREP_OWNER_DECISION_REQUIRED = 'A3_PREP_OWNER_DECISION_REQUIRED';

export const A3_PREP_OWNER_DECISIONS = {
  SET_R_TRACK_REDUCTION:
    'A3_PREP_OWNER_DECISION_REQUIRED:SET_R_TRACK_A_B_PAGE_SCORE_REDUCTION_UNDEFINED',
  SET_R_EXACT_DUPLICATE_SCORE_REDUCTION:
    'A3_PREP_OWNER_DECISION_REQUIRED:SET_R_EXACT_DUPLICATE_SCORE_REDUCTION_UNDEFINED',
  SD7_SHORT_TEXT_SELECTION:
    'A3_PREP_OWNER_DECISION_REQUIRED:SD7_SHORT_TEXT_SAMPLE_SURVIVOR_UNDEFINED',
  SD7_ORDER_DEPENDENT_SD9:
    'A3_PREP_OWNER_DECISION_REQUIRED:SD7_SURVIVOR_ORDER_CAN_CHANGE_SD9',
  SD7_UNAUDITABLE_COMPONENT:
    'A3_PREP_OWNER_DECISION_REQUIRED:SD7_COMPONENT_EXCEEDS_EXACT_ORDER_AUDIT_GUARD',
  ORGANISATION_SHARE_MULTI_VIOLATOR_TRUNCATION:
    'A3_PREP_OWNER_DECISION_REQUIRED:ORGANISATION_SHARE_MULTI_VIOLATOR_TRUNCATION_ORDER_UNDEFINED',
} as const;

export type A3PrepOwnerDecision =
  (typeof A3_PREP_OWNER_DECISIONS)[keyof typeof A3_PREP_OWNER_DECISIONS];

export class A3PrepStop extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'A3PrepStop';
  }
}
