/**
 * PHASE 2B-2D — A3 CORPUS TOOLING PREPARATION CONTRACT.
 *
 * Frozen constants are copied from Methodology V2 R3 / Corpus Acquisition Plan
 * V1. Unresolved semantics are named separately and fail closed.
 *
 * PURE: no filesystem, database, network, clock, environment or randomness.
 */
export const SET_P_RANK_SALT = 'SET_P_V2_R2';
export const SET_R_RANK_SALT = 'SET_R_V2_R2';

export const SET_P_MAX_PAGES_PER_ORGANISATION = 8;
export const SET_R_MAX_PAGES_PER_ORGANISATION = 4;

export const ORGANISATION_GATE_SHARE_CAP_NUMERATOR = 1;
export const ORGANISATION_GATE_SHARE_CAP_DENOMINATOR = 10;

export const MIN_PAGES_PER_ORGANISATION = 4;

export const REQUIRED_SPLIT_ORGANISATION_COUNTS = {
  DEV_TRAIN: 20,
  DEV_CONFIRM: 45,
  FINAL_HOLDOUT: 45,
} as const;

export const REQUIRED_TOTAL_ORGANISATIONS = 110;

export const A3_PREP_OWNER_DECISION_REQUIRED = 'A3_PREP_OWNER_DECISION_REQUIRED';

export const A3_PREP_OWNER_DECISIONS = {
  SET_R_TRACK_REDUCTION:
    'A3_PREP_OWNER_DECISION_REQUIRED:SET_R_TRACK_A_B_PAGE_SCORE_REDUCTION_UNDEFINED',
  SET_R_EXACT_DUPLICATE_SCORE_REDUCTION:
    'A3_PREP_OWNER_DECISION_REQUIRED:SET_R_EXACT_DUPLICATE_SCORE_REDUCTION_UNDEFINED',
  SD7_SHORT_TEXT_SELECTION:
    'A3_PREP_OWNER_DECISION_REQUIRED:SD7_SHORT_TEXT_SAMPLE_SURVIVOR_UNDEFINED',
  SD7_SD9_SAMPLE_RANK:
    'A3_PREP_OWNER_DECISION_REQUIRED:SD7_SAMPLE_SPECIFIC_SURVIVOR_RANK_MAKES_SD9_POOL_UNDEFINED',
  ORGANISATION_SHARE_TRUNCATION:
    'A3_PREP_OWNER_DECISION_REQUIRED:ORGANISATION_SHARE_TRUNCATION_FIXED_POINT_UNDEFINED',
  SET_R_TARGET_200:
    'A3_PREP_OWNER_DECISION_REQUIRED:SET_R_TARGET_200_EXCEEDS_STRUCTURAL_CEILING_180',
} as const;

export type A3PrepOwnerDecision =
  (typeof A3_PREP_OWNER_DECISIONS)[keyof typeof A3_PREP_OWNER_DECISIONS];

export class A3PrepStop extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'A3PrepStop';
  }
}
